apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name.ingress" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.name.service" . }}
                port:
                  number: {{ .Values.port }}
