apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name.deployment" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  selector:
    app: {{ include "app.name.deployment" . }}
    tier: {{ .Values.network.tier }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
