apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels:
    tier: {{ .Values.network.tier }}
spec:
  selector:
    app: {{ .Values.name }}
    tier: {{ .Values.network.tier }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
