# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Image and Deploy

on:
  release:
    types: [ published ]

jobs:
  dockerhub:
    name: "Build Docker Hub Image"
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            malave/gs-rest-service:latest
            malave/gs-rest-service:${{ github.ref }}
            malave/gs-rest-service:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
  deployment:
    name: "Helm install"
    runs-on: 'ubuntu-latest'
    needs: [ dockerhub ]
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v1'
      - name: 'Deploy'
        uses: 'deliverybot/helm@master'
        with:
          namespace: springservice
          release: springservice
          token: '${{ github.token }}'
          version: '${{ github.ref }}'
          chart: './servicechart'
          helm: helm3
          timeout: 10m0s
          value-files: "./servicechart/values.yaml"
          values: |
            image:
              tag: "${{ github.ref }}"
            network:
              host: ${{ secrets.KUBE_HOST }}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
